### ISSUE TITLE
Create issue for the changes with link for the commit

### ISSUE THREAD

**Issue by bgervan** [EdJoPaTo/website-stalker#186]
It would be great if we can use the notifier config to create an issue in github action. I am planning to use to detect API change for SDK package, so I can see I have action to do.

If the formatted text can be reached, we can setup Github action to create issue with that description or use Github Action to notify on unsupported platforms as well.

**Comment by EdJoPaTo** [comment]
You should be able to define every webhook there is.

Personally I want to change this kind of functionality (see https://github.com/EdJoPaTo/website-stalker/discussions/172#discussioncomment-4677023). You can join in and suggest how you would like things.
