### ISSUE TITLE
[Feature request] Convert relative links to absolute

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#24]
**Is your feature request related to a problem? Please describe.**
I use `html_markdownify` in my config. Most of the pages I'm watching use relative links making them unclickable.

**Describe the solution you'd like**
Convert the relative links to absolute so they are clickable.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by EdJoPaTo** [comment]
I thought about that.
Mainly that sparked two questions:
- Is this only a feature of the `html_markdownify` then? How about `hmtl_prettify` which also contains links. Maybe a good solution might be to introduce a new editor for this?
- What about other links? Image source, CSS/JavaScript includes, … While `html_markdownify` doesnt have something like that images could be added later on.

Any thoughts on that?

**Comment by rEnr3n** [comment]
> * Is this only a feature of the `html_markdownify` then? How about `hmtl_prettify` which also contains links.

I have not used it but I guess it should be.

> Maybe a good solution might be to introduce a new editor for this?

Yes. This should be optional.

> * What about other links? Image source, CSS/JavaScript includes, … While `html_markdownify` doesnt have something like that images could be added later on.

This should apply to all kinds of links.

**Comment by EdJoPaTo** [comment]
There is now a new editor `html_url_canonicalize` introduced in e51baf089de20c7af8c50d11ea4d149969b39aab which will be available with 0.12.0.
It works way better than I expected in my testing so far.

Thanks for bringing this up!
