### ISSUE TITLE
What's the purpose of `from:`?

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#37]
**Describe your goal**
I just followed the example and put my email address instead.

**Expected**
I expected my email address but it's not showing up on git logs. This is what I see in the log instead `Author: website-stalker/0.12.1 <website-stalker-git-commit@edjopato.de>`

**Comment by EdJoPaTo** [comment]
From is used as an HTTP Header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/From
Its also linked in the README but its not very obvious currently. Any ideas how to improve that?

The idea here is to provide a way to be contacted. As every user of this tool can for example use the tool every minute the website providers can contact you and say "something is wrong, please fix that". The alternative there is to just get blocked.

Besides the tool is being called "stalker" I want to be nice to the hosts of the websites. I dont want to spam them and I want to at least provide a way to be contacted. If they use it or just block the requests is on their side then.

**Comment by rEnr3n** [comment]
When I installed this app the first time, I looked at the the main instructions of the usage. The ones inside ```. The other details like the link you gave are automatically skipped by my eyes.

When I go back looking for some reference, I went to the config example. From there I read more stuff and read slowly.

I suggest adding explanation of `From` inside config example.

---

Another thing, could you enable discussions for this repo?

**Comment by EdJoPaTo** [comment]
Do you think fc6707e is helpful? Do you have other suggestions?

**Comment by rEnr3n** [comment]
Sorry. I actually meant below [Config Example](https://github.com/EdJoPaTo/website-stalker#config-example) and above [Editors](https://github.com/EdJoPaTo/website-stalker#editors), an h3 header on its own. I don't frequently read comments on the config example. It happened one time only. I tend to frequent the `Editors` like a glossary.

**Comment by EdJoPaTo** [comment]
I think this should help now: ec411a0

**Comment by rEnr3n** [comment]
Thank you much! :smile:
