### ISSUE TITLE
Use environment variable for `from`

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#44]
**Is your feature request related to a problem? Please describe.**
I'll take your repo here as example: https://github.com/EdJoPaTo/website-stalker-example
If someone forks/clones that repo and run it as is, your email address will be visible to those websites. It would look as if it was you who ran it instead of the one who forked/cloned it.

**Describe the solution you'd like**
`from` should also be looked up at an environment variable.

**Comment by EdJoPaTo** [comment]
I added this back in 94e4bd427c27b01e3b54cc0e9b10173135048b56 which will be part of v0.16.0.

This can be used to override a config value:
```bash
export WEBSITE_STALKER_FROM=my-email-address
```
